### ISSUE TITLE
matx 1.8.1 feature TODO list

### ISSUE THREAD

**Issue by vermouth1992** [bytedance/matxscript#116]
- Support lambda function in trace.
- Support lambda function in script.
- Infer None Return type if not annotated.
- Infer dummy __init__ function if not specified.
- Support tracing a scripted op.
- Improve error message of running a tracing module.
- Support positional arguments and kwargs as in the original function.

**Comment by cloud-mxd** [comment]
Please split it into multiple issues and associate it with the milestone of v1.8.1. Thanks @vermouth1992

**Comment by vermouth1992** [comment]
Split into multiple issues.
