### ISSUE TITLE
signed warnings

### ISSUE THREAD

**Issue by lilothar** [bytedance/matxscript#249]
when try matx, it warnings lot about signed type check, for example, string_ref, function size() return a int64_t type, why not using size_t type? the second, when link libpcre, why not using static link, dynamic link to it why not using systems pcre?

**Comment by jc-bytedance** [comment]
The decision to avoid using size_t stems from the fact that its size is dependent on the platform. Opting for the signed version helps to standardize our return type to Python. As for not utilizing system PCRE, it is a matter of maintaining consistency.

**Comment by lilothar** [comment]
thanks your anwser
