### ISSUE TITLE
add __call__ in JITModule to wrap run function.

### ISSUE THREAD

**Issue by vermouth1992** [bytedance/matxscript#63]
Calling run function each time is tedious. We can create a __call__ to allow user directly run JITModule.

**Comment by cloud-mxd** [comment]
Good idea!
Can you help to fix that?

**Comment by vermouth1992** [comment]
Fixed in 4caeea3d397aca3e1e8e8ef17a09a427354e6ec8

**Comment by cloud-mxd** [comment]
Thanks
