### ISSUE TITLE
Some feedbacks for using matxscript 1.7 to trace a pytorch model

### ISSUE THREAD

**Issue by FireBrother** [bytedance/matxscript#64]
I tried using matxscript 1.7 to trace a pytorch model and here are some feedbacks.

1. When constructing an array, you cannot use a tuple as the shape, otherwise you will report an error at compile time, and the error message will be difficult to read.
![783cdb45-42b1-4f23-9dca-45997374bbc9](https://user-images.githubusercontent.com/15845174/205614400-aacf1775-e5e6-4714-b664-399b78ac8d58.jpeg)
2. It would be nice to provide a traceable function for applying instance-wise ops to batches. For example, Cutter/Jieba and WordPieceTokenizerOp provides __call__ function only for str/bytes, but usually we need to deal with a batch of inputs. One way is to manually provide a function for packing and unpacking the input and output. I choose to use matx.pmap to keep the codes clean, however I don't expect the parallel feature and the overhead.
Also, it would be nice to make NDArray.tolist() traceable.
```python
class Pipeline:
    ...
    def preprocess(self, queries: List[bytes]):
        batch_tokens = matx.pmap(self.PreProcess, queries)
        input_ids = self.InputBuilder(batch_tokens)
        return input_ids

    def postprocess(self, logits: List[List[int]]):
        return matx.pmap(self.PostProcess, logits)

    def process(self, queries: List[bytes]):
        input_ids = self.preprocess(queries)
        infer_res = self.TorchModel(input_ids)
        logits = self.Unwrap(infer_res)
        ret_tokens = self.postprocess(logits)
        return ret_tokens
```
4. The matx.pmap converts the op with the same names, which is kind of unreadable.
![dd03637f-db63-4883-a25e-0a6fbe30e521](https://user-images.githubusercontent.com/15845174/205615942-77d8ebc0-ce22-416a-8fec-56bb34d8ae22.jpeg)
5. **matx.script(model) will hide the error message of a pytorch model**
* without matx.script:
![image](https://user-images.githubusercontent.com/15845174/205618230-148e222d-76fd-4ae8-9e3d-d6b77ade5a61.png)
* with matx.script:
![image](https://user-images.githubusercontent.com/15845174/205618209-cc47abd4-19da-42b7-8a8e-4b3f006f5aae.png)
6. Some warnings for matx.pmap are misleading. The first argument is an op, which should be a constant.
![5d0a353d-870f-4546-83dc-a04e93dfb311](https://user-images.githubusercontent.com/15845174/205617503-4a1203ee-3c3c-4d31-b859-ae30cb4ded88.jpeg)

**Comment by cloud-mxd** [comment]
Thanks for the very detailed feedback. We will fixing these issues in the version 1.8.0.
Can you help with some of these issues?

**Comment by cloud-mxd** [comment]
> When constructing an array, you cannot use a tuple as the shape, otherwise you will report an error at compile time, and the error message will be difficult to read.

Can you help fix this issue together? @bhshu

**Comment by FireBrother** [comment]
> Thanks for the very detailed feedback. We will fix these issues in the version 1.8.0. Can you help with some of these issues?

with pleasure

**Comment by vermouth1992** [comment]
Can you provide a runnable script that reproduce these issues?

**Comment by cloud-mxd** [comment]
related pr: #67
