### ISSUE TITLE
Documentation link in README.txt leads to 404

### ISSUE THREAD

**Issue by mkvalor** [bytedance/matxscript#8]
Hello.  While logged into github, I clicked the Documentation link at the top of the README page for this repo, which anchors this link:
https://github.com/bytedance/matxscript/blob/main

but this only produced 404 page not found.

**Comment by jc-bytedance** [comment]
Hello mkvalor, our team is still working on some details of the doc. We will fix the link as soon as the doc is ready. Sorry for the inconvenience.

**Comment by jc-bytedance** [comment]
Just a quick update, you can now visit https://bytedance.github.io/matxscript/ to read the draft version. The link is not updated yet as we are still working on he draft.
